import {
  arbeidsavklaringspengerUrl,
  aktivitetsplanUrl,
  arbeidssokerRegistreringUrl,
  arbeidUrl,
  foreldrepengerUrl,
  fullmakterUrl,
  hjelpemidlerUrl,
  meldekortInfoUrl,
  pensjonUrl,
  personopplysningerUrl,
  pleiepengerUrl,
  skjemaerUrl,
  sosialhjelpUrl,
  stillingerUrl,
  stillingsokUrl,
  sykefravaerUrl,
  uforetrygdUrl,
} from "./api/urls";

export const lenker = {
  ledigeStillinger: {
    nb: "Ledige stillinger",
    nn: "Ledige stillingar",
    en: "Job listings",
    url: stillingerUrl,
  },
  uforetrygd: {
    nb: "Uføretrygd",
    nn: "Uføretrygd",
    en: "Disability benefit",
    url: uforetrygdUrl,
  },
  dineForeldrepenger: {
    nb: "Dine foreldrepenger",
    nn: "Dine foreldrepengar",
    en: "My parental benefit",
    url: foreldrepengerUrl,
  },
  aktivitetsplan: {
    nb: "Aktivitetsplan",
    nn: "Aktivitetsplan",
    en: "Activity plan",
    url: aktivitetsplanUrl,
  },
  meldekort: {
    nb: "Meldekort",
    nn: "Meldekort",
    en: "Employment status form",
    url: meldekortInfoUrl,
  },
  personopplysninger: {
    nb: "Personopplysninger",
    nn: "Personopplysningar",
    en: "Personal data",
    url: personopplysningerUrl,
  },
  skjemaer: {
    nb: "Skjemaer",
    nn: "Skjema",
    en: "Forms",
    url: skjemaerUrl,
  },
  dinPensjon: {
    nb: "Din pensjon",
    nn: "Din pensjon",
    en: "My pension",
    url: pensjonUrl,
  },
  dineStillingssok: {
    nb: "Dine stillingssøk",
    nn: "Dine stillingssøk",
    en: "My job searches",
    url: stillingsokUrl,
  },
  veilederArbeidssoker: {
    nb: "Veileder for arbeidssøker",
    nn: "Rettleiar for arbeidssøkar",
    en: "Guide for job seekers",
    url: arbeidUrl,
  },
  registrerDegSomArbeidssoker: {
    nb: "Registrer deg som arbeidssøker",
    nn: "Registrer deg som arbeidssøkar",
    en: "Register as a job seeker",
    url: arbeidssokerRegistreringUrl,
  },
  sosialhjelp: {
    nb: "Økonomisk sosialhjelp",
    nn: "Økonomisk sosialhjelp",
    en: "Financial assistance",
    url: sosialhjelpUrl,
  },
  dineFullmakter: {
    nb: "Dine fullmakter",
    nn: "Dine fullmakter",
    en: "My authorizations",
    url: fullmakterUrl,
  },
  dinePleiepenger: {
    nb: "Dine pleiepenger",
    nn: "Dine pleiepengar",
    en: "My attendance allowance",
    url: pleiepengerUrl,
  },
  dittSykefravaer: {
    nb: "Ditt sykefravær",
    nn: "Ditt sjukefravær",
    en: "My absences due to sickness",
    url: sykefravaerUrl,
  },
  hjelpemidler: {
    nb: "Hjelpemidler",
    nn: "Hjelpemiddel",
    en: "Assistive technology",
    url: hjelpemidlerUrl,
  },
  arbeidsavklaringspenger: {
    nb: "Arbeidsavklaringspenger",
    nn: "Arbeidsavklaringspengar",
    en: "Work assessment allowance",
    url: arbeidsavklaringspengerUrl,
  },
};

export const generelleLenker = [
  lenker.ledigeStillinger,
  lenker.aktivitetsplan,
  lenker.personopplysninger,
  lenker.uforetrygd,
  lenker.meldekort,
  lenker.dineFullmakter,
  lenker.sosialhjelp,
  lenker.registrerDegSomArbeidssoker,
  lenker.dinePleiepenger,
  lenker.dineForeldrepenger,
  lenker.dineStillingssok,
  lenker.hjelpemidler,
];

export const oppfolgingsLenker = [
  lenker.sosialhjelp,
  lenker.arbeidsavklaringspenger,
  lenker.dinPensjon,
  lenker.dineFullmakter,
  lenker.dittSykefravaer,
  lenker.uforetrygd,
  lenker.dinePleiepenger,
  lenker.skjemaer,
  lenker.hjelpemidler,
  lenker.meldekort,
  lenker.dineForeldrepenger,
  lenker.personopplysninger,
];
