name: Deploy to dev
on: workflow_dispatch

jobs:
  permissions:
    contents: 'read'
    id-token: 'write'
    packages: 'write'
  deploy:
    uses: navikt/tms-deploy/.github/workflows/mikrofrontend-deploy.yaml@main
    with:
      cluster: '["dev-gcp"]'
      node-version: 18
    secrets: inherit